- name: checkout ebpf_exporter
  git: repo=https://github.com/kofonfor/ebpf_exporter.git dest=/root/ebpf_exporter version=bbaa2ae1aa3e9e104b82c40563afa0f6793a313a

- name: install linux-headers-{{ ansible_kernel }}
  apt: name="linux-headers-{{ ansible_kernel }}"

- name: make ebpf_exporter
  shell: cd /root/ebpf_exporter && make creates=/root/ebpf_exporter/release/ebpf_exporter-1.1.0-14-gbbaa2ae.tar.gz

- name: download ebpf_exporter
  copy: remote_src=yes src=/root/ebpf_exporter/release/ebpf_exporter-1.1.0-14-gbbaa2ae.tar.gz dest=/root/ebpf_exporter.tar.gz

- name: unpack ebpf_exporter
  unarchive: copy=no src="/root/ebpf_exporter.tar.gz" dest=/opt

- name: create a link
  file: src=/opt/ebpf_exporter-1.1.0-14-gbbaa2ae/ebpf_exporter dest=/opt/ebpf_exporter state=link

- name: put /etc/ebpf_exporter_config.yaml
  template: src=ebpf_exporter_config.yaml dest=/etc/ebpf_exporter_config.yaml backup=yes
