- name: checkout ebpf_exporter
  git: repo=https://github.com/cloudflare/ebpf_exporter.git dest=/root/ebpf_exporter version=9780ba5c53c7894423caa8fa168f0570a15c6138

- name: install linux-headers-{{ ansible_kernel }}
  apt: name="linux-headers-{{ ansible_kernel }}"

- name: make ebpf_exporter
  shell: cd /root/ebpf_exporter && make creates=/root/ebpf_exporter/release/ebpf_exporter-1.2.2-4-g9780ba5.tar.gz

- name: download ebpf_exporter
  copy: remote_src=yes src=/root/ebpf_exporter/release/ebpf_exporter-1.2.2-4-g9780ba5.tar.gz dest=/root/ebpf_exporter.tar.gz

- name: unpack ebpf_exporter
  unarchive: copy=no src="/root/ebpf_exporter.tar.gz" dest=/opt

- name: create a link
  file: src=/opt/ebpf_exporter-1.2.2/ebpf_exporter dest=/opt/ebpf_exporter state=link

- name: put /etc/ebpf_exporter_config.yaml
  template: src=ebpf_exporter_config.yaml dest=/etc/ebpf_exporter_config.yaml backup=yes
